all:
  children:
    todoapp_servers:
      hosts:
        todoapp-prod-1:
          ansible_host: ${ALB_DNS_NAME}
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          server_role: web
          environment: production
        todoapp-prod-2:
          ansible_host: ${ALB_DNS_NAME}
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          server_role: web
          environment: production
      vars:
        ansible_python_interpreter: /usr/bin/python3
        app_name: todoapp
        app_user: ec2-user
        app_dir: /opt/todoapp
        git_repo: https://github.com/yourusername/django-todo-app.git
        git_branch: main
        django_settings_module: todo_project.settings
        static_root: /opt/todoapp/staticfiles
        media_root: /opt/todoapp/media
