# Production Environment Variables
environment: production
debug: false

# Application URLs
app_url: "https://{{ domain_name | default(alb_dns_name) }}"
api_url: "https://{{ domain_name | default(alb_dns_name) }}/api/"

# Email Configuration
email_backend: django.core.mail.backends.smtp.EmailBackend
email_host: smtp.gmail.com
email_port: 587
email_use_tls: true
email_host_user: "{{ vault_email_user }}"
email_host_password: "{{ vault_email_password }}"

# Cache Configuration
cache_backend: django_redis.cache.RedisCache
cache_location: "redis://{{ redis_host }}:{{ redis_port }}/1"

# Session Configuration
session_engine: django.contrib.sessions.backends.cache
session_cache_alias: default
session_cookie_age: 1209600  # 2 weeks

# Security Settings
secure_ssl_redirect: true
session_cookie_secure: true
csrf_cookie_secure: true
secure_hsts_seconds: 31536000  # 1 year
secure_hsts_include_subdomains: true
secure_hsts_preload: true

# Logging Configuration
logging_handlers:
  - console
  - file
  - syslog

# Performance Settings
django_use_cache: true
django_cache_timeout: 300
django_use_compression: true
